In [3]:
import pandas as pd

In [6]:
# create
data={
    "name":["a","b","c"],
    "age":[45,19,24]
}
df=pd.DataFrame(data)
df

  name  age
0    a   45
1    b   19
2    c   24

##### ---------------------- وارد کردن دیتا----------------------

In [87]:
df=pd.read_csv("./data.csv")
df

      name  age  salary
0   maryam   34   20000
1    zahra   20   15000
2   najmeh   32   18000
3   shirin   18   10000
4   nasrin   22   18000
5     ziba   26   22000
6  nazanin   32   28000

In [88]:
df.head()

     name  age  salary
0  maryam   34   20000
1   zahra   20   15000
2  najmeh   32   18000
3  shirin   18   10000
4  nasrin   22   18000

In [89]:
df.describe()

             age        salary
count   7.000000      7.000000
mean   26.285714  18714.285714
std     6.473389   5618.845840
min    18.000000  10000.000000
25%    21.000000  16500.000000
50%    26.000000  18000.000000
75%    32.000000  21000.000000
max    34.000000  28000.000000

In [90]:
df['name']

0     maryam
1      zahra
2     najmeh
3     shirin
4     nasrin
5       ziba
6    nazanin
Name: name, dtype: str

In [91]:
df.iloc[3,:]

name      shirin
age           18
salary     10000
Name: 3, dtype: object

In [92]:
df.iloc[4,[0,1]]

name    nasrin
age         22
Name: 4, dtype: object

In [93]:
# filter
filter_df=df[df["age"]>=25]
filter_df

      name  age  salary
0   maryam   34   20000
2   najmeh   32   18000
5     ziba   26   22000
6  nazanin   32   28000

In [94]:
#  sort
sort_df=df.sort_values("age",ascending=True)
sort_df

      name  age  salary
3   shirin   18   10000
1    zahra   20   15000
4   nasrin   22   18000
5     ziba   26   22000
2   najmeh   32   18000
6  nazanin   32   28000
0   maryam   34   20000

In [95]:
df

      name  age  salary
0   maryam   34   20000
1    zahra   20   15000
2   najmeh   32   18000
3   shirin   18   10000
4   nasrin   22   18000
5     ziba   26   22000
6  nazanin   32   28000

In [96]:
#subset  انتخاب بخش مشخص از دیتا  

subset=df.loc[2:5,['name','salary']]
subset

     name  salary
2  najmeh   18000
3  shirin   10000
4  nasrin   18000
5    ziba   22000

In [97]:
#group     مثلا گروه بندی سن

grouped_df=df.groupby('age')
grouped_df

In [98]:
grouped_df.count()

     name  salary
age
18      1       1
20      1       1
22      1       1
26      1       1
32      2       2
34      1       1

In [99]:
#add a new column
df['test']=[1,2,3,4,5,6,7]
df

      name  age  salary  test
0   maryam   34   20000     1
1    zahra   20   15000     2
2   najmeh   32   18000     3
3   shirin   18   10000     4
4   nasrin   22   18000     5
5     ziba   26   22000     6
6  nazanin   32   28000     7

In [100]:
# delete a column
#  axis =1    ستونی
#  axis =0    سطری
df.drop('test',axis =1,inplace=True)
df

      name  age  salary
0   maryam   34   20000
1    zahra   20   15000
2   najmeh   32   18000
3   shirin   18   10000
4   nasrin   22   18000
5     ziba   26   22000
6  nazanin   32   28000

In [101]:
len(df)

7

In [102]:
#add a new row
df.loc[len(df)]={
    'name':'vaji',
    'age':'22'
}
df

      name age   salary
0   maryam  34  20000.0
1    zahra  20  15000.0
2   najmeh  32  18000.0
3   shirin  18  10000.0
4   nasrin  22  18000.0
5     ziba  26  22000.0
6  nazanin  32  28000.0
7     vaji  22      NaN

# -------------------------------

In [103]:
df.isna()

    name    age  salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False
7  False  False    True

In [104]:
df.dropna()

      name age   salary
0   maryam  34  20000.0
1    zahra  20  15000.0
2   najmeh  32  18000.0
3   shirin  18  10000.0
4   nasrin  22  18000.0
5     ziba  26  22000.0
6  nazanin  32  28000.0

 در پیش پردازش ها کاملا متداول است که مقادیر نامشخص را  با صفر یا میانگین داده ها جایگزین کنیم

In [114]:
mean_salary=df['salary'].mean()
df2=df.fillna(0)
df3=df.fillna(mean_salary)
df2,df3

(      name age   salary
 0   maryam  34  20000.0
 1    zahra  20  15000.0
 2   najmeh  32  18000.0
 3   shirin  18  10000.0
 4   nasrin  22  18000.0
 5     ziba  26  22000.0
 6  nazanin  32  28000.0
 7     vaji  22      0.0,
       name age        salary
 0   maryam  34  20000.000000
 1    zahra  20  15000.000000
 2   najmeh  32  18000.000000
 3   shirin  18  10000.000000
 4   nasrin  22  18000.000000
 5     ziba  26  22000.000000
 6  nazanin  32  28000.000000
 7     vaji  22  18714.285714)

In [115]:
# write
df.to_csv('new_data.csv')